### ISSUE TITLE
implement backoff strategy when hitting rate limit on planetary computer

### ISSUE THREAD

**Issue by cmosig** [cmosig/sentle#9]
Something like exponential backoff in time if one hits the rate limit. This ensures that one can just leave the process running until everything is done, even if progress are slow. 

Need to check for http code 429.
https://github.com/microsoft/PlanetaryComputer/discussions/347#discussioncomment-9572550

**Comment by cmosig** [comment]
finally the rate limit again

```
During handling of the above exception, another exception occurred:                                                                                            
                                                                                                                                                               
Traceback (most recent call last):                                                                                                                             
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/pystac_client/stac_api_io.py", line 215, in request                            
    resp = self.session.send(prepped, timeout=self.timeout, **send_kwargs)                                                                                     
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                     
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/requests/sessions.py", line 703, in send                                       
    r = adapter.send(request, **kwargs)                                                                                                                        
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                        
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/requests/adapters.py", line 691, in send                                       
    raise RetryError(e, request=request)                                                                                                                       
requests.exceptions.RetryError: HTTPSConnectionPool(host='planetarycomputer.microsoft.com', port=443): Max retries exceeded with url: /api/stac/v1/search (Caus
ed by ResponseError('too many 504 error responses'))                                                                                                           
                                                                                                                                                               
During handling of the above exception, another exception occurred:                                                                                            
                                                                                                                                                               
Traceback (most recent call last):                                                                                                                             
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/joblib/_utils.py", line 72, in __call__                                        
    return self.func(**kwargs)                                                                                                                                 
           ^^^^^^^^^^^^^^^^^^^                                                                                                                                 
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/joblib/parallel.py", line 598, in __call__                                     
    return [func(*args, **kwargs)                                                                                                                              
            ^^^^^^^^^^^^^^^^^^^^^                                                                                                                              
  File "/net/home/cmosig/projects/sentle/sentle/sentle.py", line 97, in process_ptile                                                                          
    item_list = catalog_search_ptile(                                                                                                                          
                ^^^^^^^^^^^^^^^^^^^^^                                                                                                                          
  File "/net/home/cmosig/projects/sentle/sentle/sentle.py", line 54, in catalog_search_ptile                                                                   
    top=bound_top)).item_collection())                                                                                                                         
                    ^^^^^^^^^^^^^^^^^                                                                                                                          
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/pystac_client/item_search.py", line 763, in item_collection                    
    feature_collection = self.item_collection_as_dict.__wrapped__(self)                                                                                        
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                        
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/pystac_client/item_search.py", line 784, in item_collection_as_dict            
    for page in self.pages_as_dicts():                                                                                                                         
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/pystac_client/item_search.py", line 734, in pages_as_dicts                     
    for page in self._stac_io.get_pages(                                                                                                                       
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/pystac_client/stac_api_io.py", line 297, in get_pages                          
    page = self.read_json(url, method=method, parameters=parameters)                                                                                           
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                           
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/pystac/stac_io.py", line 205, in read_json                                     
    txt = self.read_text(source, *args, **kwargs)                                                                                                              
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                              
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/pystac_client/stac_api_io.py", line 168, in read_text                          
    return self.request(href, *args, **kwargs)                                                                                                                 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                 
  File "/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/pystac_client/stac_api_io.py", line 218, in request                            
    raise APIError(str(err))
pystac_client.exceptions.APIError: HTTPSConnectionPool(host='planetarycomputer.microsoft.com', port=443): Max retries exceeded with url: /api/stac/v1/search (C
aused by ResponseError('too many 504 error responses'))
```
